version: '3.9'

services:
  postgres:
    image: postgres:13.3
    container_name: postgres_pushnotification
    restart: always
    networks:
      - internal
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
    - "${POSTGRES_EXTERNAL_PORT:-5432}:5432"
    volumes:
    - postgres_data:/var/lib/postgresql/data
    profiles:
      - db

  web:
    image: "${IMAGE_URL}"
    container_name: web_pushnotification
    restart: always
    networks:
      - internal
      - load-balancer
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_EMAIL=${EMAIL}
      - ConnectionStrings__DefaultConnection=${CONNECTION_STRING}
      - IdentityServer__Key__Password=${IdentityServer_Password}
      - IdentityServer__Key__Base64Certificate=${IdentityServer_Base64Certificate}
      - REACT_APP_SENTRY_DSN=${SENTRY_DSN}
      - Sentry__Dsn=${SENTRY_DSN}
      - REACT_APP_CLIENT_KEY=${WEB_CLIENT_KEY}
      - Swagger__ClientPublicKey=${WEB_CLIENT_KEY}
      - IdentityServer__Clients__0__ClientSecrets__0__Value=${WEB_CLIENT_SECRET}
      - IdentityServer__Clients__1__ClientSecrets__0__Value=${MOBILE_CLIENT_SECRET}
      - Logging__Remote__Server=${LOGGING_SERVER}
      - Logging__Remote__Port=${LOGGING_PORT}
      - Logging__Remote__Token=${LOGGING_TOKEN}
      - Logging__Remote__InstanceName=${LOGGING_INSTANCE}
      - SignUrl__Secret=${SIGN_URL_SECRET}

  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy_pushnotification
    restart: always
    networks:
      - load-balancer
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    volumes:
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - ./nginx/conf.d/proxy.conf:/etc/nginx/conf.d/proxy.conf:ro
      - ./nginx/conf.d/compression.conf:/etc/nginx/conf.d/compression.conf:ro
      - ./nginx/vhost.d/default_location:/etc/nginx/vhost.d/default_location:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    profiles:
      - nginx

  acme:
    image: nginxproxy/acme-companion
    container_name: acme_pushnotification
    restart: always
    depends_on:
      - "nginx-proxy"
    volumes:
      - acme:/etc/acme.sh:rw
      - vhost:/etc/nginx/vhost.d:rw
      - html:/usr/share/nginx/html:rw
      - certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - DEFAULT_EMAIL=${EMAIL}
      - NGINX_PROXY_CONTAINER=nginx-proxy_pushnotification
    profiles:
      - nginx

networks:
  load-balancer:
    external: true
  internal:

volumes:
  acme:
  vhost:
  html:
  certs:
  postgres_data:
